"""
Metric definitions for the business-plan-skills country context scraper.

Structure per metric:
  - "name":       Human-readable metric name
  - "indicator":  World Bank API indicator code (None = no WB equivalent; use portal scraper)
  - "unit":       Unit string written into the CSV
  - "source":     Primary source label written into the CSV

World Bank API pattern:
  https://api.worldbank.org/v2/country/{ISO3}/indicator/{indicator}?format=json&per_page=10&mrv=1

ISO3 codes used in scraper:
  Uganda = UGA, Kenya = KEN, Tanzania = TZA
  (Add more by extending COUNTRY_CONFIGS in scrape_metrics.py)
"""

METRICS = [

    # ── 1. MACROECONOMIC HEALTH ──────────────────────────────────────────────
    {
        "category": "Macroeconomic Health",
        "name": "GDP (current USD billions)",
        "indicator": "NY.GDP.MKTP.CD",
        "unit": "USD billions",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "GDP per capita (current USD)",
        "indicator": "NY.GDP.PCAP.CD",
        "unit": "USD",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Real GDP growth rate (%)",
        "indicator": "NY.GDP.MKTP.KD.ZG",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Inflation rate, CPI (%)",
        "indicator": "FP.CPI.TOTL.ZG",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Gross capital formation (% of GDP)",
        "indicator": "NE.GDI.TOTL.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Current account balance (% of GDP)",
        "indicator": "BN.CAB.XOKA.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "FDI net inflows (% of GDP)",
        "indicator": "BX.KLT.DINV.WD.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Government expenditure (% of GDP)",
        "indicator": "GC.XPN.TOTL.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Tax revenue (% of GDP)",
        "indicator": "GC.TAX.TOTL.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Macroeconomic Health",
        "name": "Central government debt (% of GDP)",
        "indicator": "GC.DOD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },

    # ── 2. SME DYNAMICS ──────────────────────────────────────────────────────
    {
        "category": "SME Dynamics",
        "name": "Time to start a business (days)",
        "indicator": "IC.REG.DURS",
        "unit": "days",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Cost to start a business (% of GNI per capita)",
        "indicator": "IC.REG.COST.PC.ZS",
        "unit": "% GNI per capita",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Procedures to start a business (count)",
        "indicator": "IC.REG.PROC",
        "unit": "procedures",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "New business density (per 1,000 adults)",
        "indicator": "IC.BUS.NDNS.ZS",
        "unit": "per 1,000 adults",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Time to register property (days)",
        "indicator": "IC.PRP.DURS",
        "unit": "days",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Total tax and contribution rate (% of profit)",
        "indicator": "IC.TAX.TOTL.CP.ZS",
        "unit": "% of profit",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Time to pay taxes (hours per year)",
        "indicator": "IC.TAX.DURS",
        "unit": "hours/year",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Domestic credit to private sector (% of GDP)",
        "indicator": "FS.AST.PRVT.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "SME Dynamics",
        "name": "Time to resolve insolvency (years)",
        "indicator": "IC.ISV.DURS",
        "unit": "years",
        "source": "World Bank Doing Business",
    },
    {
        "category": "SME Dynamics",
        "name": "Cost of enforcing a contract (% of claim)",
        "indicator": "IC.LGL.COST.ZS",
        "unit": "% of claim",
        "source": "World Bank Doing Business",
    },

    # ── 3. DIGITAL INFRASTRUCTURE ────────────────────────────────────────────
    {
        "category": "Digital Infrastructure",
        "name": "Internet users (% of population)",
        "indicator": "IT.NET.USER.ZS",
        "unit": "%",
        "source": "World Bank WDI / ITU",
    },
    {
        "category": "Digital Infrastructure",
        "name": "Mobile cellular subscriptions (per 100 people)",
        "indicator": "IT.CEL.SETS.P2",
        "unit": "per 100 people",
        "source": "World Bank WDI / ITU",
    },
    {
        "category": "Digital Infrastructure",
        "name": "Fixed broadband subscriptions (per 100 people)",
        "indicator": "IT.NET.BBND.P2",
        "unit": "per 100 people",
        "source": "World Bank WDI / ITU",
    },
    {
        "category": "Digital Infrastructure",
        "name": "Secure internet servers (per million people)",
        "indicator": "IT.NET.SECR.P6",
        "unit": "per million people",
        "source": "World Bank WDI",
    },
    {
        "category": "Digital Infrastructure",
        "name": "ICT goods exports (% of total goods exports)",
        "indicator": "TX.VAL.ICTG.ZS.UN",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Digital Infrastructure",
        "name": "ICT service exports (% of service exports, BoP)",
        "indicator": "BX.GSR.CCIS.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Digital Infrastructure",
        "name": "High-technology exports (% of manufactured exports)",
        "indicator": "TX.VAL.TECH.MF.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Digital Infrastructure",
        "name": "Individuals using the internet, female (%)",
        "indicator": "IT.NET.USER.FE.ZS",
        "unit": "%",
        "source": "World Bank WDI / ITU",
    },
    {
        "category": "Digital Infrastructure",
        "name": "E-government development index (UN)",
        "indicator": None,
        "unit": "index (0–1)",
        "source": "UN E-Government Survey",
    },
    {
        "category": "Digital Infrastructure",
        "name": "Mobile network coverage — 3G/4G (% population)",
        "indicator": None,
        "unit": "%",
        "source": "ITU Datahub",
    },

    # ── 4. FINANCIAL INCLUSION ───────────────────────────────────────────────
    {
        "category": "Financial Inclusion",
        "name": "Account ownership at financial institution (% adults 15+)",
        "indicator": "FX.OWN.TOTL.ZS",
        "unit": "% adults 15+",
        "source": "World Bank Global Findex",
    },
    {
        "category": "Financial Inclusion",
        "name": "Account ownership — female (% females 15+)",
        "indicator": "FX.OWN.TOTL.FE.ZS",
        "unit": "% females 15+",
        "source": "World Bank Global Findex",
    },
    {
        "category": "Financial Inclusion",
        "name": "Borrowed from financial institution (% adults 15+)",
        "indicator": "FX.IFS.CRED.ZS",
        "unit": "% adults 15+",
        "source": "World Bank Global Findex",
    },
    {
        "category": "Financial Inclusion",
        "name": "Lending interest rate (%)",
        "indicator": "FR.INR.LEND",
        "unit": "%",
        "source": "World Bank WDI / Central Bank",
    },
    {
        "category": "Financial Inclusion",
        "name": "Deposit interest rate (%)",
        "indicator": "FR.INR.DPST",
        "unit": "%",
        "source": "World Bank WDI / Central Bank",
    },
    {
        "category": "Financial Inclusion",
        "name": "Interest rate spread (lending minus deposit, %)",
        "indicator": "FR.INR.LNDP",
        "unit": "percentage points",
        "source": "World Bank WDI",
    },
    {
        "category": "Financial Inclusion",
        "name": "Commercial bank branches (per 100,000 adults)",
        "indicator": "FB.CBK.BRCH.P5",
        "unit": "per 100,000 adults",
        "source": "World Bank WDI / IMF FAS",
    },
    {
        "category": "Financial Inclusion",
        "name": "ATMs (per 100,000 adults)",
        "indicator": "FB.ATM.TOTL.P5",
        "unit": "per 100,000 adults",
        "source": "World Bank WDI / IMF FAS",
    },
    {
        "category": "Financial Inclusion",
        "name": "Mobile money account (% adults 15+)",
        "indicator": "FX.OWN.TOTL.MA.ZS",
        "unit": "% adults 15+",
        "source": "World Bank Global Findex",
    },
    {
        "category": "Financial Inclusion",
        "name": "Remittances received (% of GDP)",
        "indicator": "BX.TRF.PWKR.DT.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },

    # ── 5. REAL ESTATE & INFRASTRUCTURE ──────────────────────────────────────
    {
        "category": "Real Estate & Infrastructure",
        "name": "Access to electricity (% of population)",
        "indicator": "EG.ELC.ACCS.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Access to clean fuels for cooking (% of population)",
        "indicator": "EG.CFT.ACCS.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Electric power consumption (kWh per capita)",
        "indicator": "EG.USE.ELEC.KH.PC",
        "unit": "kWh per capita",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Urban population (% of total)",
        "indicator": "SP.URB.TOTL.IN.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Urban population growth (% annual)",
        "indicator": "SP.URB.GROW",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "People using safely managed drinking water (% of population)",
        "indicator": "SH.H2O.SMDW.ZS",
        "unit": "%",
        "source": "World Bank WDI / WHO-UNICEF JMP",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "People using safely managed sanitation (% of population)",
        "indicator": "SH.STA.SMSS.ZS",
        "unit": "%",
        "source": "World Bank WDI / WHO-UNICEF JMP",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Renewable electricity output (% of total)",
        "indicator": "EG.ELC.RNEW.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Roads, total network (km)",
        "indicator": "IS.ROD.TOTL.KM",
        "unit": "km",
        "source": "World Bank WDI",
    },
    {
        "category": "Real Estate & Infrastructure",
        "name": "Rail lines (total route-km)",
        "indicator": "IS.RRS.TOTL.KM",
        "unit": "route-km",
        "source": "World Bank WDI",
    },

    # ── 6. EDUCATION & EDTECH ─────────────────────────────────────────────────
    {
        "category": "Education & EdTech",
        "name": "Literacy rate, adults total (% of people 15+)",
        "indicator": "SE.ADT.LITR.ZS",
        "unit": "%",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Youth literacy rate (% ages 15–24)",
        "indicator": "SE.ADT.1524.LT.ZS",
        "unit": "%",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Primary school enrolment (% gross)",
        "indicator": "SE.PRM.ENRR",
        "unit": "% gross",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Secondary school enrolment (% gross)",
        "indicator": "SE.SEC.ENRR",
        "unit": "% gross",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Tertiary school enrolment (% gross)",
        "indicator": "SE.TER.ENRR",
        "unit": "% gross",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Government expenditure on education (% of GDP)",
        "indicator": "SE.XPD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Primary school completion rate (% of relevant age group)",
        "indicator": "SE.PRM.CMPT.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Education & EdTech",
        "name": "Pupil-teacher ratio, primary",
        "indicator": "SE.PRM.ENRL.TC.ZS",
        "unit": "pupils per teacher",
        "source": "World Bank WDI / UNESCO",
    },
    {
        "category": "Education & EdTech",
        "name": "Human Capital Index (World Bank)",
        "indicator": "HD.HCI.OVRL",
        "unit": "index (0–1)",
        "source": "World Bank HCP",
    },
    {
        "category": "Education & EdTech",
        "name": "PISA mean score — reading (OECD/PISA, where available)",
        "indicator": None,
        "unit": "score",
        "source": "OECD PISA",
    },

    # ── 7. DEMOGRAPHICS & LABOUR ──────────────────────────────────────────────
    {
        "category": "Demographics & Labour",
        "name": "Population, total",
        "indicator": "SP.POP.TOTL",
        "unit": "persons",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Population growth rate (% annual)",
        "indicator": "SP.POP.GROW",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Population ages 0–14 (% of total)",
        "indicator": "SP.POP.0014.TO.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Population ages 65+ (% of total)",
        "indicator": "SP.POP.65UP.TO.ZS",
        "unit": "%",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Life expectancy at birth (years)",
        "indicator": "SP.DYN.LE00.IN",
        "unit": "years",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Fertility rate, total (births per woman)",
        "indicator": "SP.DYN.TFRT.IN",
        "unit": "births per woman",
        "source": "World Bank WDI",
    },
    {
        "category": "Demographics & Labour",
        "name": "Labour force participation rate, total (% of ages 15+)",
        "indicator": "SL.TLF.ACTI.ZS",
        "unit": "%",
        "source": "World Bank WDI / ILO",
    },
    {
        "category": "Demographics & Labour",
        "name": "Unemployment, total (% of labour force)",
        "indicator": "SL.UEM.TOTL.ZS",
        "unit": "%",
        "source": "World Bank WDI / ILO",
    },
    {
        "category": "Demographics & Labour",
        "name": "Youth unemployment (% of youth labour force ages 15–24)",
        "indicator": "SL.UEM.1524.ZS",
        "unit": "%",
        "source": "World Bank WDI / ILO",
    },
    {
        "category": "Demographics & Labour",
        "name": "Employment in agriculture (% of total employment)",
        "indicator": "SL.AGR.EMPL.ZS",
        "unit": "%",
        "source": "World Bank WDI / ILO",
    },

    # ── 8. GOVERNMENT & REGULATION ────────────────────────────────────────────
    {
        "category": "Government & Regulation",
        "name": "Control of corruption (Worldwide Governance Indicator)",
        "indicator": "CC.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "Rule of law (Worldwide Governance Indicator)",
        "indicator": "RL.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "Government effectiveness (Worldwide Governance Indicator)",
        "indicator": "GE.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "Regulatory quality (Worldwide Governance Indicator)",
        "indicator": "RQ.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "Political stability and absence of violence (WGI)",
        "indicator": "PV.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "Voice and accountability (Worldwide Governance Indicator)",
        "indicator": "VA.EST",
        "unit": "estimate (−2.5 to +2.5)",
        "source": "World Bank WGI",
    },
    {
        "category": "Government & Regulation",
        "name": "CPI Transparency International score (0–100)",
        "indicator": None,
        "unit": "score (0=most corrupt, 100=clean)",
        "source": "Transparency International CPI",
    },
    {
        "category": "Government & Regulation",
        "name": "Patent applications, residents (count)",
        "indicator": "IP.PAT.RESD",
        "unit": "applications",
        "source": "World Bank WDI / WIPO",
    },
    {
        "category": "Government & Regulation",
        "name": "Trademark applications, total (count)",
        "indicator": "IP.TMK.TOTL",
        "unit": "applications",
        "source": "World Bank WDI / WIPO",
    },
    {
        "category": "Government & Regulation",
        "name": "IMF Article IV — most recent assessment year",
        "indicator": None,
        "unit": "year",
        "source": "IMF Country Reports",
    },

    # ── 9. TRADE & LOGISTICS ──────────────────────────────────────────────────
    {
        "category": "Trade & Logistics",
        "name": "Trade (% of GDP)",
        "indicator": "NE.TRD.GNFS.ZS",
        "unit": "% of GDP",
        "source": "World Bank WDI",
    },
    {
        "category": "Trade & Logistics",
        "name": "Merchandise exports (current USD millions)",
        "indicator": "TX.VAL.MRCH.CD.WT",
        "unit": "USD millions",
        "source": "World Bank WDI / WTO",
    },
    {
        "category": "Trade & Logistics",
        "name": "Merchandise imports (current USD millions)",
        "indicator": "TM.VAL.MRCH.CD.WT",
        "unit": "USD millions",
        "source": "World Bank WDI / WTO",
    },
    {
        "category": "Trade & Logistics",
        "name": "Services exports (BoP, current USD millions)",
        "indicator": "BX.GSR.NFSV.CD",
        "unit": "USD millions",
        "source": "World Bank WDI",
    },
    {
        "category": "Trade & Logistics",
        "name": "Logistics Performance Index — overall (1–5)",
        "indicator": "LP.LPI.OVRL.XQ",
        "unit": "score (1=low, 5=high)",
        "source": "World Bank LPI",
    },
    {
        "category": "Trade & Logistics",
        "name": "Tariff rate, applied, simple mean — all products (%)",
        "indicator": "TM.TAX.MRCH.SM.AR.ZS",
        "unit": "%",
        "source": "World Bank WDI / WTO",
    },
    {
        "category": "Trade & Logistics",
        "name": "Container port traffic (TEUs, 20-foot equivalents)",
        "indicator": "IS.SHP.GOOD.TU",
        "unit": "TEUs",
        "source": "World Bank WDI",
    },
    {
        "category": "Trade & Logistics",
        "name": "Air transport, freight (million tonne-km)",
        "indicator": "IS.AIR.GOOD.MT.K1",
        "unit": "million tonne-km",
        "source": "World Bank WDI / ICAO",
    },
    {
        "category": "Trade & Logistics",
        "name": "Foreign direct investment, net inflows (USD millions)",
        "indicator": "BX.KLT.DINV.CD.WD",
        "unit": "USD millions",
        "source": "World Bank WDI",
    },
    {
        "category": "Trade & Logistics",
        "name": "Remittances received (USD millions)",
        "indicator": "BX.TRF.PWKR.CD.DT",
        "unit": "USD millions",
        "source": "World Bank WDI",
    },

    # ── 10. SOCIO-ECONOMIC & CONSUMER ─────────────────────────────────────────
    {
        "category": "Socio-Economic & Consumer",
        "name": "Poverty headcount ratio at $2.15/day, 2017 PPP (% of population)",
        "indicator": "SI.POV.DDAY",
        "unit": "%",
        "source": "World Bank Poverty & Inequality Platform",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "GINI index (World Bank estimate)",
        "indicator": "SI.POV.GINI",
        "unit": "index (0=equal, 100=unequal)",
        "source": "World Bank Poverty & Inequality Platform",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Household final consumption per capita (constant 2015 USD)",
        "indicator": "NE.CON.PRVT.PC.KD",
        "unit": "constant 2015 USD",
        "source": "World Bank WDI",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Health expenditure per capita (current USD)",
        "indicator": "SH.XPD.CHEX.PC.CD",
        "unit": "USD",
        "source": "World Bank WDI / WHO",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Out-of-pocket health expenditure (% of current health expenditure)",
        "indicator": "SH.XPD.OOPC.CH.ZS",
        "unit": "%",
        "source": "World Bank WDI / WHO",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Hospital beds (per 1,000 people)",
        "indicator": "SH.MED.BEDS.ZS",
        "unit": "per 1,000 people",
        "source": "World Bank WDI / WHO",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Physicians (per 1,000 people)",
        "indicator": "SH.MED.PHYS.ZS",
        "unit": "per 1,000 people",
        "source": "World Bank WDI / WHO",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Maternal mortality ratio (per 100,000 live births)",
        "indicator": "SH.STA.MMRT",
        "unit": "per 100,000 live births",
        "source": "World Bank WDI / WHO",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Under-5 mortality rate (per 1,000 live births)",
        "indicator": "SH.DYN.MORT",
        "unit": "per 1,000 live births",
        "source": "World Bank WDI / UNICEF",
    },
    {
        "category": "Socio-Economic & Consumer",
        "name": "Prevalence of undernourishment (% of population)",
        "indicator": "SN.ITK.DEFC.ZS",
        "unit": "%",
        "source": "World Bank WDI / FAO",
    },
]

# Country configurations
# Keys: lowercase country name matching country-context/ directory name
# iso3: World Bank / UN ISO 3166-1 alpha-3 code
COUNTRY_CONFIGS = {
    "uganda": {
        "iso3": "UGA",
        "iso2": "UG",
        "display_name": "Uganda",
    },
    "kenya": {
        "iso3": "KEN",
        "iso2": "KE",
        "display_name": "Kenya",
    },
    "tanzania": {
        "iso3": "TZA",
        "iso2": "TZ",
        "display_name": "Tanzania",
    },
    "rwanda": {
        "iso3": "RWA",
        "iso2": "RW",
        "display_name": "Rwanda",
    },
    "ethiopia": {
        "iso3": "ETH",
        "iso2": "ET",
        "display_name": "Ethiopia",
    },
    "ghana": {
        "iso3": "GHA",
        "iso2": "GH",
        "display_name": "Ghana",
    },
    "nigeria": {
        "iso3": "NGA",
        "iso2": "NG",
        "display_name": "Nigeria",
    },
    "south-africa": {
        "iso3": "ZAF",
        "iso2": "ZA",
        "display_name": "South Africa",
    },
}
